Toni img centered, quotes fixed in Toni's pressRelease.
PlatformOfTrust/marketing-app pull request #15
Opened 2019-07-24 08:48 UTC by kumardennis

2019-07-24 11:37 UTC, edanchenkov commented on src/styles/global.css
> +body blockquote {
Don't you have this change in another branch?

2019-07-24 11:37 UTC, edanchenkov approved these changes

2019-07-24 12:03 UTC, kumardennis commented on src/styles/global.css
> +body blockquote {
yeah that was for another press Release in a different task, this is a different task for toni.

2019-07-25 14:28 UTC, edanchenkov commented
@kumardennis  Merge conflict

2019-07-29 10:31 UTC, edanchenkov commented on src/components/Featured.js
> +import HexPic from '../images/new-bg-square-smaller2.jpg';
Same here, do you really need to keep old image?

2019-07-29 10:32 UTC, edanchenkov requested changes
Do we really need to keep old image? See Featured.js

2019-07-29 14:53 UTC, merged