Feature/small-changes
PlatformOfTrust/marketing-app pull request #2
Opened 2019-07-16 13:00 UTC by kumardennis

Adding missing texts, fixing some spacing issues, changing pictures.

2019-07-18 12:10 UTC, victorv-sbp requested changes

2019-07-18 12:10 UTC, victorv-sbp commented on src/pages/cases.js
> +    h2 { font-size: 1.6rem; letter-spacing: 0.01em; word-spacing: 0.065em; line-height: 1.2em;}
Use multiple lines for definition to keep consistency with other classes.

2019-07-18 12:10 UTC, victorv-sbp commented on src/components/Footer.js
> +                    <br/>
Recommended to use styling instead of `<br/>`

2019-07-18 14:30 UTC, kumardennis commented on src/components/Footer.js
> +                    <br/>
done

2019-07-19 07:11 UTC, edanchenkov commented
@kumardennis Update your PR to point to `develop`

2019-07-19 14:24 UTC, edanchenkov commented on src/templates/news-list-template.js
> +  width: width: 100%;
That's nice 🙂. I wonder if this is applied and what affect it could have.

2019-07-19 14:25 UTC, edanchenkov approved these changes
There are lot of things we are going to change in the future. Especially in legacy code. But right now it is ok.

2019-07-22 12:26 UTC, merged