FAQ
PlatformOfTrust/marketing-app pull request #24
Opened 2019-07-27 10:06 UTC by kumardennis

2019-07-27 19:24 UTC, edanchenkov commented
@kumardennis Checks for your PR fail, look above. Fix those first.

2019-07-27 19:25 UTC, edanchenkov requested changes
Fix PR checks aka marketing app test pipeline in azure and fix merge conflicts.

2019-07-27 19:26 UTC, edanchenkov commented on src/styles/global.css
> +  background: rgb(255, 250, 250, 0.3); /*probably should make a var for this */
Yes, create var for it from colors Nazia posted. You can use darken or lighten or similar scss functions to adjust color to your taste.

2019-07-27 19:28 UTC, edanchenkov commented on src/components/Featured.js
> +import HexPic from '../images/new-bg-square-smaller2.jpg';
How this image is different from the old one? You should try to not add new images to the repo. If old version of image is not used than replace it with a new one, instead of adding new one as a separate image.

2019-07-28 18:57 UTC, kumardennis commented on src/components/Featured.js
> +import HexPic from '../images/new-bg-square-smaller2.jpg';
this image is square cropped, 1st is for the header image of the artilcle, and 2nd is for the thumbnail on the news page. i think this was the pattern legacy code was following. But yeah i will add new one as seperate from next time.

2019-07-28 19:08 UTC, kumardennis commented on src/styles/global.css
> +  background: rgb(255, 250, 250, 0.3); /*probably should make a var for this */
thye dont have seperate css file for variables so i added it in the same file.

2019-07-28 19:09 UTC, kumardennis commented on src/styles/global.css
> +  background: rgb(255, 250, 250, 0.3); /*probably should make a var for this */
or should i make the seperate file?

2019-07-28 19:13 UTC, kumardennis commented on src/components/Featured.js
> +import HexPic from '../images/new-bg-square-smaller2.jpg';
i misread, so i should delete the old one from this commit?

2019-07-29 07:40 UTC, edanchenkov commented on src/styles/global.css
> +  background: rgb(255, 250, 250, 0.3); /*probably should make a var for this */
Oh true this is css, not scss. Well then you should probably just leave it as is. We need to start using scss for marketing app as well.

2019-07-29 08:24 UTC, edanchenkov commented on src/components/Featured.js
> +import HexPic from '../images/new-bg-square-smaller2.jpg';
If `new-bg-square-smaller` is not used anywhere else. You should replace `new-bg-square-smaller` with `new-bg-square-smaller2`. Not creating new file `new-bg-square-smaller2`.

2019-07-29 11:59 UTC, edanchenkov approved these changes

2019-07-29 12:03 UTC, victorv-sbp approved these changes

2019-07-29 13:41 UTC, merged